### ISSUE TITLE
unescaped $ in add-aur.sh causes error in aur-install 

### ISSUE THREAD

**Issue by Godhart** [greyltc-org/docker-archlinux-aur#6]
I believe that escaping slash is missing before '$' char in `add-aur.sh` on line #77
```
...
tee /bin/aur-install <<EOF
#!/bin/sh
if test "$#" -ne 0
then
...
```

`if test "$#" -ne 0` should be changed to `if test "\$#" -ne 0`

Without this bugfix first line in aur-install looks like `if test "0" -ne 0` which obviously is incorrect

**Comment by greyltc** [comment]
thanks!
